---
title: "STAT 331 Final Project"
author: "Noel Lopez, Patrick George, Riley Svensson, Ningjing Hua"
format: 
  html:
    self-contained: true
    code-tools: true
    toc: true
    number-sections: true
    theme: 
      dark: superman
    code-fold: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

```{r setup}
library(tidyverse)
energy <- read.csv("https://raw.githubusercontent.com/patrickgeorge12/stat-331-PA6/main/eg_fec_rnew_zs.csv", check.names = FALSE)
co2 <- read.csv("https://raw.githubusercontent.com/patrickgeorge12/stat-331-PA6/main/yearly_co2_emissions_1000_tonnes.csv", check.names = FALSE)

```

```{r clean data}

if(`﻿country` %in% colnames(energy))
{
  energy <- energy |> rename(country = `﻿country`)
}

if(`﻿country` %in% colnames(co2))
{
  co2 <- co2 |> rename(country = `﻿country`)
}

energy_clean <- energy |>
  pivot_longer(cols = !country,
               names_to = "year",
               values_to = "Percent_Consumption")

co2_clean <- co2 |> 
    select(country,`1989`:`2017`) |>
    pivot_longer(cols = !country,
               names_to = "year",
               values_to = "1000_metric_tonnes")

co2_clean <- co2_clean |>
   mutate(thousand_metric_tons = case_when(
    str_detect(`1000_metric_tonnes`, "k") ~ 
      as.integer(str_replace(`1000_metric_tonnes`, "k", "")) * 1000,
    str_detect(`1000_metric_tonnes` , "M") ~ 
      as.integer(str_replace(`1000_metric_tonnes` , "M", '')) * 1000000,
    TRUE ~ as.numeric(`1000_metric_tonnes`))) |>
  select(country, year, thousand_metric_tons)

master <- left_join(co2_clean, energy_clean) |> 
  drop_na()
```
